### ISSUE TITLE
Add Custom Certificate for Status Pages

### ISSUE THREAD

**Issue by kmillervc** [squadcastHQ/squadcast-support#16]
**Is your feature request related to a problem you are facing? Please describe.**
The current status pages use the statuspage.io certificate which causes a browser warning on CNAME entry

**Describe the ideal solution that could solve this problem for you**
Provide the ability to provide our own ssl certificate or automatically generate one using something like Let's Encrypt

**What alternatives did you consider?**
None.  Reverse proxy will not work for subscription notifications

**Additional Context**
None

**Comment by raghuchinnannan** [comment]
Hi @kmillervc ,

We neither support custom SSL certificates nor use other domain certificates. 

As you suggested, we use LetsEncrypt to auto-generate the certificates for your Status subdomain. The problem here seems like your CAA records are set to allow only Godaddy to issue certificates. I If you can add a CAA record with letsencrypt.org as the issuer to either the root domain or just the status page sub-domain,  it’ll start working and be served via https.

We will update our documentation so other users can understand this clearly.

**Comment by raghuchinnannan** [comment]
Additional note, even if you change the CAA records, it might take an hour or so for the changes to take effect due to DNS propagation and Letsencrypt certificate attempt rate limiting.

**Comment by kmillervc** [comment]
Thanks.  Changes have been made on my part.
